# -*- coding: utf-8 -*-
"""Anexo a la guia de Sysme TPV: balanza, impresora y cajon en la instalacion real."""
from maqueta import Doc

d = Doc("Anexo_Sysme_Balanza_Impresora_Cajon_FA.pdf",
        "Sysme TPV - Anexo: balanza, impresora y cajon (Futura Admin)",
        "Futura Admin · Anexo a la guía de Sysme TPV")

d.portada(
    "SYSME TPV",
    "Anexo: balanza, impresora y cajón",
    ["Lo que pasó al conectar los cacharros de verdad",
     "y cómo se resolvió, paso a paso.",
     "",
     "Continúa la Guía de instalación y configuración",
     "(secciones 21 a 27)."],
    ["USO INTERNO · EQUIPO DE FUTURA ADMIN",
     "Complementa las secciones 10, 11 y 12 de la guía.",
     "Leer antes de conectar una balanza por serie."],
    ["Instalación en La Tienda de Tere · 25 de septiembre de 2026",
     "Futura Admin · septiembre de 2026"])

d.indice("ÍNDICE DEL ANEXO", [
    "LA BALANZA",
    (21, "Error EComPort / PurgeComm al arrancar"),
    (22, "Configuración que quedó en la Epelsa 56 PPI"),
    (23, "Cómo se calculan las posiciones del peso"),
    (24, "Si en Datos recibidos no sale nada"),
    (25, "La balanza arranca en OFF (pendiente)"),
    "IMPRESORA Y CAJÓN",
    (26, "La impresora Approx appPOS80AM"),
    (27, "El cajón portamonedas: secuencias y diagnóstico"),
])

# -------------------------------------------------- BALANZA
d.separador("LA BALANZA", "EPELSA 56 PPI POR SERIE",
            ["El error del primer día, la configuración que quedó",
             "y cómo leer la cadena que manda la balanza."])

d.pagina(21, "ERROR ECOMPORT / PURGECOMM AL ARRANCAR", [
    "# Lo que sale en pantalla",
    "Exception EComPort in module Tpv.exe. PurgeComm function failed (win error code: 22).",
    "",
    "# Qué significa",
    "Sysme abre el puerto COM de la balanza y lo primero que hace es vaciarlo (PurgeComm).",
    "El código 22 es ERROR_BAD_COMMAND: el dispositivo o su driver no entiende la orden.",
    "No es un fallo de la configuración de Sysme: es el puerto o el driver.",
    "",
    "# Causa en esta instalación",
    "El adaptador USB-serie es un Prolific PL2303GT. Con el driver que pone Windows solo,",
    "falla justo al vaciar el puerto. Se resolvió instalando el driver oficial de Prolific.",
    "",
    "# Cómo se resuelve",
    "> 1.  Instalar el driver actual de Prolific (PL23XX Windows Driver Installer).",
    "> 2.  Desenchufar y volver a enchufar el adaptador. Reiniciar el PC.",
    "> 3.  Administrador de dispositivos → Puertos (COM y LPT): tiene que salir",
    "      Prolific PL2303GT USB Serial COM Port (COM3), sin triángulo amarillo.",
    "> 4.  Poner ese mismo COM en Sysme y reiniciar Sysme.",
    "",
    "# Otras causas del mismo error",
    "* El COM configurado en Sysme no existe o es de otro aparato.",
    "* El adaptador se desconecta o Windows lo apaga para ahorrar energía.",
    "* Otro periférico de Sysme (visor, cajón) apunta a un COM inexistente.",
], None,
    truco=["DÓNDE SE VE EL COM",
           "Configuración de Windows → Bluetooth y dispositivos → Dispositivos, en Otros",
           "dispositivos. Las impresoras NO salen ahí: están en Impresoras y escáneres."])

d.pagina(22, "CONFIGURACIÓN QUE QUEDÓ EN LA EPELSA 56 PPI", [
    "Ruta: SISTEMA → CONFIGURACIÓN → pestaña Balanzas → subpestaña Automática",
    "",
    "# Valores con los que funciona",
    "* Habilitar Balanza Automática: marcada.",
    "* Puerto: COM3 (adaptador Prolific PL2303GT).",
    "* Modo Comando: marcado, con el comando $ en la casilla de al lado.",
    "* Posición de inicio de peso (enteros): 2",
    "* Posición de fin de peso (enteros): 6",
    "* Posición de inicio de peso (decimales): 8",
    "* Posición de fin de peso (decimales): 10",
    "* Omitir peso si es inferior a: 0,000",
    "* Desactivar Balanza tras cada Pesaje: desmarcada.",
    "",
    "# Driver",
    "La balanza no lleva driver propio. Lo único que necesita Windows es el driver del",
    "adaptador USB-serie (Prolific). Si Windows ya muestra el COM, no hay que instalar más.",
    "",
    "# Comprobar siempre",
    "> 1.  Poner algo de peso conocido en el plato y pulsar Probar Balanza.",
    "> 2.  Verificar que el número coincide. Cambiar el peso y repetir.",
    "> 3.  Guardar Cambios y reiniciar Sysme.",
], None,
    ojo=["APUNTARLO EN TRELLO",
         "Estos valores son los que hay que copiar si se reinstala el equipo o se cambia",
         "el adaptador. Si cambia el COM, hay que cambiarlo también en Sysme."])

d.pagina(23, "CÓMO SE CALCULAN LAS POSICIONES DEL PESO", [
    "# Qué son",
    "La balanza no manda solo el número: manda una cadena con más cosas (estado, signo,",
    "unidad). Sysme necesita saber en qué caracteres de esa cadena está el peso.",
    "Se cuenta carácter a carácter de izquierda a derecha, contando espacios y símbolos.",
    "",
    "# Ejemplo",
    "Si con 1,250 kg en el plato la balanza manda:  ST,GS,+001.250kg",
    "* S=1  T=2  ,=3  G=4  S=5  ,=6  +=7  0=8  0=9  1=10  .=11  2=12  5=13  0=14  k=15  g=16",
    "* Enteros (001): de la posición 8 a la 10.",
    "* Decimales (250): de la posición 12 a la 14.",
    "* El punto decimal (posición 11) no se usa.",
    "",
    "# Método con una balanza nueva",
    "> 1.  Pulsar Probar Balanza con peso en el plato y hacer foto del campo",
    "      Datos recibidos de la balanza.",
    "> 2.  Localizar el número del peso y contar posiciones.",
    "> 3.  Probar contando desde 1. Si el peso sale corrido un dígito, restar 1 a las",
    "      cuatro posiciones: no está confirmado si Sysme cuenta desde 0 o desde 1.",
    "> 4.  Validar con dos pesos distintos antes de dar por buena la configuración.",
], None,
    truco=["EN LA EPELSA 56 PPI",
           "Quedó enteros 2–6 y decimales 8–10: cinco cifras de enteros, separador en la",
           "posición 7 y tres decimales."])

d.pagina(24, "SI EN DATOS RECIBIDOS NO SALE NADA", [
    "# Primero: ¿tiene salida de datos?",
    "Las balanzas PPI (Peso-Precio-Importe) no siempre traen salida para PC/TPV.",
    "Mirar si tiene conector serie (DB9 o RJ). Si solo tiene el cable de corriente,",
    "no puede mandar el peso: habría que pedir el kit de comunicación o cambiarla.",
    "",
    "# Causas habituales, por orden",
    "* Cable: las Epelsa suelen necesitar su cable de comunicación o uno cruzado",
    "  (null-modem). Un cable serie cualquiera puede no funcionar.",
    "* La balanza no está en modo comunicación PC/TPV. En muchas comerciales ese menú",
    "  está protegido o precintado: lo cambia el servicio técnico de Epelsa.",
    "* La balanza sólo manda el peso cuando se le pide. Hay que marcar Modo Comando",
    "  con el comando de petición de peso. En la Epelsa 56 PPI funcionó con $.",
    "* Salen símbolos raros: la velocidad no coincide. Lo normal es 9600, 8 bits, sin",
    "  paridad, 1 bit de parada, igual en la balanza y en las propiedades del COM3.",
    "",
    "# Qué pedir a Epelsa o al distribuidor",
    "Si tiene salida RS-232 para TPV, qué cable hace falta, cómo se activa la",
    "comunicación, a qué velocidad transmite, cuál es el comando de petición de peso",
    "y qué formato tiene la trama.",
], None)

d.pagina(25, "LA BALANZA ARRANCA EN OFF (PENDIENTE)", [
    "# El síntoma",
    "En la pantalla de venta el botón Balanza [F5] sale en OFF y hay que pulsar F5.",
    "La primera vez que se conectó salía en ON todo el rato sin tocar nada.",
    "",
    "# Lo que ya se ha descartado",
    "* Desactivar Balanza tras cada Pesaje está desmarcada.",
    "* En la pestaña Conf. de la pantalla de venta no hay opción para arrancar en ON.",
    "* En SISTEMA → CONFIGURACIÓN → Opciones tampoco.",
    "",
    "# Hipótesis 1: el Modo Comando",
    "Cuando salía en ON, probablemente aún no estaba marcado Modo Comando con $.",
    "> 1.  Desmarcar Modo Comando, Guardar Cambios y reiniciar Sysme.",
    "> 2.  Si arranca en ON y el peso llega igual, dejarlo desmarcado.",
    "> 3.  Si arranca en ON pero no llega el peso, el comando es necesario y el OFF",
    "      es comportamiento de Sysme: preguntar a su soporte.",
    "",
    "# Hipótesis 2: el puerto no se abre al arrancar",
    "* Encender la balanza ANTES de abrir Sysme.",
    "* Salir siempre con el botón SALIR para liberar el COM3.",
    "* Quitar el ahorro de energía del adaptador y de los concentradores USB.",
], None,
    ojo=["MIENTRAS TANTO",
         "Se trabaja pulsando F5 una vez al entrar en Ventas. Pregunta para soporte de",
         "Sysme: en la 5.39, con balanza automática en COM3 y Modo Comando $, ¿cómo",
         "se hace que la balanza arranque en ON en el terminal de ventas?"])

# -------------------------------------------------- IMPRESORA Y CAJON
d.separador("IMPRESORA Y CAJÓN", "APPROX APPPOS80AM",
            ["Dónde encontrar la impresora en Windows",
             "y cómo diagnosticar un cajón que no abre."])

d.pagina(26, "LA IMPRESORA APPROX APPPOS80AM", [
    "# Dónde está en Windows",
    "Configuración → Bluetooth y dispositivos → Impresoras y escáneres.",
    "No aparece en la lista de Dispositivos: eso no quiere decir que no esté instalada.",
    "",
    "# Si no aparece en Impresoras y escáneres",
    "> 1.  Encenderla y enchufarla por USB directo al PC, sin hub.",
    "> 2.  Mirar en el Administrador de dispositivos si sale como desconocido.",
    "> 3.  Instalar el driver de Approx para la appPOS80AM.",
    "> 4.  Imprimir una página de prueba desde Windows antes de tocar Sysme.",
    "",
    "# En Sysme",
    "* Elegir la impresora por el mismo nombre que tiene en Windows.",
    "* Quitar la ventana de Impresión de Documentos tras cada venta (sección 12).",
    "",
    "# Secuencias ESC/POS de referencia",
    "* Corte parcial de papel: 29,86,1  (alternativa: 29,86,66,0)",
], None,
    truco=["ES ESC/POS",
           "La appPOS80AM entiende los códigos estándar de impresora de tickets, así que",
           "valen las secuencias genéricas de ESC/POS."])

d.pagina(27, "EL CAJÓN: SECUENCIAS Y DIAGNÓSTICO", [
    "Ruta: SISTEMA → CONFIGURACIÓN → pestaña Cajón Portamonedas (modo impresora)",
    "",
    "# Secuencias probadas, en este orden",
    "* 27,112,0,25,250   (ESC p, pin 2; la estándar)",
    "* 27,112,0,50,250",
    "* 27,112,48,55,121",
    "* 27,112,1,25,250   (cajón cableado al pin 5)",
    "En la instalación no abrió con ninguna escrita desde Sysme.",
    "",
    "# Diagnóstico: separar cajón de Sysme",
    "* Llave del cajón en posición abierta. Probar la palanca de emergencia de abajo.",
    "* Cable en el conector DK / Drawer de la impresora, no en el de red.",
    "* Prueba sin Sysme: en Preferencias de la impresora, opción de cajón",
    "  Abrir antes de imprimir, e imprimir una página de prueba.",
    "* O compartir la impresora como TICKET y ejecutar en PowerShell:",
    "> [IO.File]::WriteAllBytes('C:\\cajon.bin', [byte[]](27,112,0,25,250))",
    "> cmd /c copy /b C:\\cajon.bin \\\\localhost\\TICKET",
    "",
    "# Cómo leer el resultado",
    "* Abre sin Sysme: el hardware está bien; revisar el formato que espera Sysme en",
    "  el campo de secuencia (comas, #, hexadecimal) copiando el del ejemplo.",
    "* No abre nunca: cable, cajón no compatible con impresora (24 V, RJ11/RJ12).",
], None,
    ojo=["ANOTAR LA SECUENCIA QUE FUNCIONE",
         "Cuando abra, apuntar en Trello la secuencia exacta y el formato con que se",
         "escribió en Sysme."])

d.guardar()
print("Anexo FA generado")
